### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by Squidkingdom** [jyao6429/discord-bot#7]
Hello, I have a few questions
1. Do you care if I use your code in my bot, I don't know how to use LavaPlayer so I'm looking some online sources.
2. What does you Main.logMessage() do, does it print the message back to the channel?

Thank you, Squid

**Comment by jyao6429** [comment]
1. Of course, you can use my code! It is open-source for a reason 😄 .
2. Sorry about my horrible documentation, the Main.logMessage() is for other classes to append text to the logger in the GUI.

**Comment by Squidkingdom** [comment]
:) I didn't realize at the time that you had a gui :P Thank you though!
